services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile

  presentation:
    image: presentation
    build:
      context: .
      dockerfile: src/External/Presentation/Dockerfile